[package]
name = "cairo_bootcamp_3"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
<<<<<<< HEAD
starknet = "2.8.0"
assert_macros = "2.8.0"
=======
starknet = "^2.8.4"
>>>>>>> refs/remotes/origin/main

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }
assert_macros = "2.8.4"


[[target.starknet-contract]]
# name = "CounterV2"
sierra = true

[scripts]
test = "snforge test"
