name: Run Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.4"
      
      - name: Setup snfoundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.31.0"
          
      - name: Run Starknet Foundry tests
        id: starknet_foundry_tests
        run: snforge test